// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANg13ZKQEkctGSPH_61e4gRrudZN492Ao',
    appId: '1:978597455378:web:025826306fd68860311acb',
    messagingSenderId: '978597455378',
    projectId: 'collective-action-fd893',
    authDomain: 'collective-action-fd893.firebaseapp.com',
    storageBucket: 'collective-action-fd893.firebasestorage.app',
    measurementId: 'G-9ZMRHB7JGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDceWW_oK1PrjApys3wNWRUyoTXRVHBPWA',
    appId: '1:978597455378:android:789742984b40c611311acb',
    messagingSenderId: '978597455378',
    projectId: 'collective-action-fd893',
    storageBucket: 'collective-action-fd893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb2lIBZFuf0sNWcbbVsz72a_GJuCgtTF4',
    appId: '1:978597455378:ios:44c70ea0160797a3311acb',
    messagingSenderId: '978597455378',
    projectId: 'collective-action-fd893',
    storageBucket: 'collective-action-fd893.firebasestorage.app',
    iosClientId:
        '978597455378-kucbhm6o2m3v0s7osq3b0u1kmbmuurul.apps.googleusercontent.com',
    iosBundleId: 'com.example.collectiveActionFrontend',
  );
}
